ai_camera/urls.py
from django.urls import path
from .views import (
            CameraListView,
            rtc_stream,
            ip_camera_view,
            playback,
            playback_view,
            image_loader,
            predict_image,
            get_picture_from_ip,
            load_pin_dataset
        )


urlpatterns = [
    path('', CameraListView.as_view(), name="ai_camera"),
    path('camera/<int:cam_id>/', ip_camera_view, name='camera'),
    path('camera/<int:cam_id>/playback', playback, name='playback'),
    path('camera/<int:cam_id>/playback/<int:play_id>/', playback_view, name='playback_view'),
    path('webrtc_camera/', rtc_stream, name='webrtc_camera'),
    path('image_loader/', image_loader, name='image_loader'),

    path('predict/', predict_image),
    path('get_picture_from_ip/', get_picture_from_ip),
    path('load_pin_dataset/', load_pin_dataset),
]

dFace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('researches/', include('researches.urls')),
    path('ai_camera/', include('ai_camera.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="main"),
    path('about/', views.about, name="about"),
]

ai_camera/models.py
from .constants import (
        lfw_trained_model,
        openface_model,
        pinface_trained_model,
        mtcnn,
        input_shape
    )
from django.db import models
from ndarraydjango.fields import NDArrayField
from PIL import Image as PIL_Image
from .Image import Image
from .Shape import Shape
from datetime import timedelta
import numpy as np
import cv2
import os
import re


class Camera(models.Model):
    name            = models.CharField(max_length=20,  null=False)
    ip_cam_adress   = models.CharField(max_length=20,  null=True)
    ip_cam_user     = models.CharField(max_length=10,  null=True)
    ip_cam_password = models.CharField(max_length=30,  null=True)
    description     = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.name

class PlaybackVideo(models.Model):
    camera_id   = models.ForeignKey(Camera, on_delete=models.CASCADE)
    filename    = models.CharField(max_length=50,        null=False, default="")
    headline    = models.CharField(max_length=50,        null=True)
    description = models.TextField(max_length=200,       null=True)
    video       = models.FileField(upload_to ='videos/', null=True)
    recognized  = models.BooleanField(null=False, default=False)

    def __str__(self):
        return str(self.camera_id) + ": " + self.headline

    def save(self, *args, **kwargs):
        result = re.match(r"(\d{4})(\d{2})(\d{2})(\d{6})", self.filename)
        (year, month, day, time) = result.groups()
        x = str(timedelta(seconds=int(time))).split(':')
        self.headline = "{}-{}-{}__{}".format(year, month, day, time)
        self.description = "Year:{}\nMonth:{}\nDay:{}".format(year, month, day) + \
                         "\nTime in hh:mm:ss: " + x[0] + " Hours, " + x[1] + ", Minutes " + x[2] + " Seconds."
        super(PlaybackVideo, self).save(*args, **kwargs)

class Person(models.Model):
    name  = models.TextField(max_length=50, null=False)

    PERSON_CHOISES = [
        ("staff", "staff"),
        ("student", "student"),
    ]
    career                  = models.TextField(max_length=15, null=True, choices=PERSON_CHOISES)
    image                   = models.FileField(upload_to ='images/', null=True)
    # image_original_nd_array = NDArrayField(shape=(128), dtype=np.float32, null=True)
    # image_pinfase_nd_array  = NDArrayField(shape=(128), dtype=np.float32, null=True)
    image_lfw_nd_array      = NDArrayField(shape=(128), dtype=np.float32, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        image = Image(np.asarray(PIL_Image.open(self.image))) # already RGB, so no need cv2.cvtColor
        image.resize(Shape(96, 96))
        image.normalize()

        # self.image_original_nd_array = openface_model.encode(image)
        # self.image_pinfase_nd_array  = pinface_trained_model.encode(image)
        self.image_lfw_nd_array      = lfw_trained_model.encode(image)
        super(Person, self).save(*args, **kwargs)

ai_camera/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.views import generic
from django.core.files import File
from django.http import HttpResponse
from .models import Camera, PlaybackVideo, Person
from hikvisionapi import Client
from .RecognizeAlgorithm import RecognizeAlgorithm
from .constants import (
        lfw_trained_model,
        openface_model,
        pinface_trained_model
    )
from .utils import to_base64
import numpy as np
import base64
import json
import cv2
import os


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class CameraListView(generic.ListView):
    model = Camera
    template_name = 'ai_camera/index.html'


@login_required(login_url='/login/')
def ip_camera_view(request, cam_id):
    camera = Camera.objects.get(id = cam_id)
    context = { 'camera': camera }
    return render(request, 'ai_camera/ip_camera.html', context)


@login_required(login_url='/login/')
def playback(request, cam_id):
    camera = Camera.objects.get(id = cam_id)

    if request.method == "POST":
        os.system("cd Downloads && \
                hikload --server " + camera.ip_cam_adress   + \
                " --user "         + camera.ip_cam_user     + \
                " --password "     + camera.ip_cam_password + \
                " --downloads "    + str(cam_id)            + \
                " && cd "          + str(cam_id)            + \
                " && for i in *-101.mp4; do name=`echo \"$i\" | cut -d'.' -f1`; echo \"$name\"; ffmpeg -n -i \"$i\" \"${name}-conv.mp4\"; done")

        downloads_dir = f'Downloads'
        for directory in os.listdir(downloads_dir):
            if not os.path.isdir(f'{downloads_dir}/{directory}'):
                continue
            cam_id = directory
            camera = Camera.objects.get(id = cam_id)
            for filename in os.listdir(f'{downloads_dir}/{directory}'):
                if filename.endswith("-conv.mp4"):
                    path = f'{downloads_dir}/{directory}/{filename}'
                    try:
                        playback_exist = PlaybackVideo.objects.get(filename = filename)
                    except PlaybackVideo.DoesNotExist:
                        playback_exist = None
                    if not playback_exist:
                        playback = PlaybackVideo(camera_id = camera, filename = filename)
                        with open(path, 'rb') as f:
                            data = File(f)
                            playback.video.save(filename, data, True)
                else:
                    os.remove(f'{downloads_dir}/{directory}/{filename}')


    playbacks = PlaybackVideo.objects.filter(camera_id=camera)

    context = {
            'playbacks': playbacks,
            'camera': camera
        }
    return render(request, 'ai_camera/playback.html', context)


@login_required(login_url='/login/')
def playback_view(request, cam_id, play_id):
    camera = Camera.objects.get(id = cam_id)
    playback = PlaybackVideo.objects.filter(camera_id=camera).get(id=play_id)

    if request.method == "POST":
        persons = Person.objects.all()
        if not playback.recognized:
            videos_dir = f'main/media/videos'
            for filename in os.listdir(videos_dir):
                if filename == playback.filename:
                    RecognizeAlgorithm.recognize_video(videos_dir, filename, persons, lfw_trained_model)
                    with open('{}/r-{}'.format(videos_dir, filename), 'rb') as f:
                        data = File(f)
                        playback.video.save('r-{}'.format(filename), data, True)
                    playback.recognized = True
                    playback.save()

                    os.remove(f'{videos_dir}/{filename}')
                    os.remove(f'{videos_dir}/r-{filename}')

    context = {
            'playback': playback,
            'camera': camera
        }
    return render(request, 'ai_camera/playback_view.html', context)


@login_required(login_url='/login/')
def rtc_stream(request):
    return render(request, 'ai_camera/rtc_stream.html')


@login_required(login_url='/login/')
def image_loader(request):
    return render(request, 'ai_camera/image_loader.html')


@csrf_exempt
@require_POST
def load_pin_dataset(request):
    dataset_dir = f'datasets/pin_faces'
    for directory in os.listdir(dataset_dir):
        if not os.path.isdir(f'{dataset_dir}/{directory}'):
            continue
        person_name = directory
        for filename in os.listdir(f'{dataset_dir}/{directory}'):
            if filename.endswith(".jpg"):
                path = f'{dataset_dir}/{directory}/{filename}'
                try:
                    person_exist = Person.objects.get(name = person_name)
                except Person.DoesNotExist:
                    person_exist = None

                if not person_exist:
                    person = Person(name=person_name.title())
                    with open(path, 'rb') as f:
                        data = File(f)
                        person.image.save(filename, data, True)

    return HttpResponse(request)

@csrf_exempt
@require_POST
def get_picture_from_ip(request):
    ip_cam_adress   = request.POST.get('ip_cam_adress')
    ip_cam_user     = request.POST.get('ip_cam_user')
    ip_cam_password = request.POST.get('ip_cam_password')
    cam             = Client('http://' + ip_cam_adress, ip_cam_user, ip_cam_password)
    image           = cam.Streaming.channels[102].picture(method='get', type='opaque_data')
    image = cv2.imdecode(np.fromstring(image.content, np.uint8), cv2.IMREAD_UNCHANGED)
    result = to_base64(image)

    return HttpResponse(result, content_type='image/jpeg')

@csrf_exempt
@require_POST
def predict_image(request):
    image = request.FILES.get('image')
    image = cv2.imdecode(np.fromstring(image.read(), np.uint8), cv2.IMREAD_UNCHANGED)
    persons = Person.objects.all()
    result = RecognizeAlgorithm.recognize_pic_to_json(image, persons, lfw_trained_model)
    # image = RecognizeAlgorithm.recognize_pic_to_json(image, persons, openface_model)
    # image = RecognizeAlgorithm.recognize_pic_to_json(image, persons, pinface_trained_model)

    return HttpResponse(json.dumps(result), content_type="application/json")

ai_camera/templates/ai_camera/image_loader.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  <title>Image Download</title>
{% endblock title %}

{% block content %}
  <div class="container text-center mt-3">
    <h1>Upload Image</h1>
  </div>
  {% if user.is_staff %}

    <div class="container">
      <div class="input-group">
        <input class="form-control form-control-lg" id="formFile" type="file" accept="image/jpg, image/jpeg">
        <button id="btn-predict" type="button" class="btn btn-primary btn-lg" disabled>Predict Image</button>
      </div>
    </div>

    <div class="text-center mx-4 my-3 bg-opacity-10 border border-info rounded">
      <div class="row p-3">
        <div class="col">
          <h3>Downloaded Image</h3>
          <div id="downloadedImage"></div>
        </div>
        <div class="col">
          <h3>Predicted Image</h3>
          <div id="predictedImage"></div>
        </div>
      </div>
    </div>

    <div class="container mt-3" id="predTable"></div>

  {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}

  <div class="container">
    <a href="{% url 'ai_camera' %}" type="button" class="btn btn-warning"><i class="fa-solid fa-arrow-left"></i> Go back</a>
  </div>

  <script type="module" src="{% static 'js/image_loader.js' %}"></script>
  <script type="module" src="{% static 'js/fetch_snap.js' %}"></script>
{% endblock content %}

ai_camera/templates/ai_camera/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  <title>AI_camera</title>
{% endblock title %}

{% block content %}
  {% if user.is_staff %}

    <div class="container text-center mt-3">
      <h1>AI Camera</h1>
      <p>Welcome to camera page where you are can watch in camera and work with ML</p>
      <div class="row">
        <div class="col">
          <a href="{% url 'webrtc_camera' %}" class="btn btn-primary"><i class="fa-solid fa-camera"></i> Watch on client camera with WebRTC</a>
        </div>
        <div class="col">
          <a href="{% url 'image_loader' %}" class="btn btn-primary"><i class="fa-solid fa-download"></i> Upload image for next process</a>
        </div>
        <div class="col">
          <button class="btn btn-danger" id="pin_to_db" type="submit">Load PIN dataset to database</button>
        </div>
      </div>
    </div>


    {% if camera_list.all.count > 0 %}

      <div class="container mt-3">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for camera in camera_list %}
              <tr>
                <th>{{ camera.id }}</th>
                <td><a href="{% url 'camera' camera.pk %}">{{ camera.name }}</td>
                <td>{{ camera.description }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    {% else %}
      <div class="text-center m-5">
        <h1>No IP-cameras yet</h1>
      </div>
    {% endif %}

  {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}


  <script type="module" src="{% static 'js/pin_to_db.js' %}"></script>
{% endblock content %}

ai_camera/templates/ai_camera/ip_camera.html
{% extends 'main/base.html' %}
{% load static %}

{% block b_st %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/camera.css' %}">
{% endblock b_st %}

{% block title %}
  <title>IP_camera</title>
{% endblock title %}

{% block content %}
  <div class="container text-center">
    <h1>IP-camera</h1>
    <p>Welcome to ip-camera page where you are can watch in ip-camera and work with ML</p>
  </div>
  {% if user.is_staff %}

  <div class="container text-center">
    <div class="row">
      <div class="col">
        <h3>{{camera.name}}</h3><p>User: {{camera.ip_cam_user}}, Password: {{camera.ip_cam_password}}</p>
      </div>
      <div class="col align-self-center">
        <button class="btn btn-warning" id="btn-capture" type="button" onclick="captureSnapshot('{{camera.ip_cam_adress}}', '{{camera.ip_cam_user}}', '{{camera.ip_cam_password}}')">
          <i class="fa-solid fa-camera-retro"></i> Capture Image
        </button>
        <button id="btn-predict" type="button" class="btn btn-primary" disabled>Predict Image</button>
      </div>
      <div class="col align-self-center">
        <a href="{% url 'playback' camera.pk %}" class="btn btn-info"><i class="fa-solid fa-film"></i> Watch downloaded playback from camera</a>
      </div>
    </div>
  </div>

    <div class="m-2 bg-opacity-10 border border-info rounded">
      <div class="row text-center p-3">
        <div class="col">
          <h3>The Stream</h3>
          <iframe id="ipcam_frame" width="645" height="485" src="http://{{camera.ip_cam_adress}}/ISAPI/Streaming/channels/102/httpPreview"></iframe>
        </div>
        <div class="col">
          <h3>The Capture</h3>
          <div id="snapshot"></div>
        </div>
      </div>
    </div>

    <div class="container mt-3" id="predTable"></div>

  {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}

  <div class="container">
    <a href="{% url 'ai_camera' %}" type="button" class="btn btn-warning"><i class="fa-solid fa-arrow-left"></i> Go back</a>
  </div>

  <script type="module" src="{% static 'js/ip_camera.js' %}"></script>
  <script type="module" src="{% static 'js/fetch_snap.js' %}"></script>
{% endblock content %}

ai_camera/templates/ai_camera/playback.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  <title>IP_camera</title>
{% endblock title %}

{% block content %}
  {% if user.is_staff %}
    <div class="container text-center mt-3">
      <div class="row">
        <div class="col align-self-center">
          <h1>Playback</h1>
        </div>
        <div class="col align-self-center">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-success" type="submit">Download latest playbacks from camera: {{camera.name}}</button>
          </form>
        </div>
      </div>
    </div>
    {% if playbacks.all.count > 0 %}

      <div class="container mt-3">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Playback</th>
              <th scope="col">Recognized</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for playback in playbacks %}
              <tr>
                <th>{{ playback.id }}</th>
                <td><a href="{% url 'playback_view' camera.pk playback.pk %}"><i class="fa-solid fa-video"></i> {{ playback.headline }}</a><br></td>
                <td>{{ playback.recognized }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    {% else %}
      <div class="text-center m-5">
        <h1>No playbacks yet</h1>
      </div>
    {% endif %}
  {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}

  <div class="container">
    <a href="{% url 'camera' camera.pk %}" type="button" class="btn btn-warning"><i class="fa-solid fa-arrow-left"></i> Go back</a>
  </div>

{% endblock content %}

ai_camera/templates/ai_camera/playback_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  <title>IP_camera</title>
{% endblock title %}

{% block content %}
  {% if user.is_staff %}

    <div class="container text-center mt-3">
      <div class="row">
        <div class="col align-self-center">
          <h1>{{playback.headline}}</h1>
          <h4>{{playback.description}}</h4>
        </div>
        <div class="col align-self-center">
          <form method="post">
            {% csrf_token %}

            {% if playback.recognized %}
              <button class="btn btn-success" type="submit" disabled>Recognoze playback video</button>
            {% else %}
              <button class="btn btn-success" type="submit">Recognoze playback video</button>
            {% endif %}
          </form>
        </div>
      </div>
    </div>

    <div class="video-container text-center mt-3">
      <video controls="" preload="auto" height="720" width="1280">
        <source src="{{playback.video.url}}" type="video/mp4" />
      </video>
    </div>

  {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}

  <div class="container">
    <a href="{% url 'playback' camera.pk %}" type="button" class="btn btn-warning"><i class="fa-solid fa-arrow-left"></i> Go back</a>
  </div>

{% endblock content %}

ai_camera/templates/ai_camera/rtc_stream.html
{% extends 'main/base.html' %}
{% load static %}

{% block b_st %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/camera.css' %}">
{% endblock b_st %}

{% block title %}
  <title>WebRTC_Camera</title>
{% endblock title %}


{% block content %}
  {% if user.is_staff %}

    <div class="px-4 pt-2">
      <button id="btn-start"   type="button" class="btn btn-success">Start Streaming</button>
      <button id="btn-stop"    type="button" class="btn btn-danger"  disabled>Stop Streaming</button>
      <button id="btn-capture" type="button" class="btn btn-warning" disabled>Capture Image</button>
      <button id="btn-predict" type="button" class="btn btn-primary" disabled>Predict Image</button>
    </div>


    <!-- Video Element & Canvas -->
    <div class="text-center mx-4 my-3 bg-opacity-10 border border-info rounded">
      <div class="row p-3">
        <div class="col">
          <h3>The Stream</h3>
          <video id="stream" width="640" height="480"></video>
        </div>
        <div class="col">
          <h3>The Capture</h3>
          <canvas id="canvas" width="640" height="480"></canvas>
          <div id="snapshot"></div>
        </div>
      </div>
    </div>

    <div class="container mt-3" id="predTable"></div>

    {% else %}
    <p>You have no rights to visit this page</p>
  {% endif %}

  <div class="container">
    <a href="{% url 'ai_camera' %}" type="button" class="btn btn-warning"><i class="fa-solid fa-arrow-left"></i> Go back</a>
  </div>

  <script type="module" src="{% static 'js/rtc_camera.js' %}"></script>
  <script type="module" src="{% static 'js/fetch_snap.js' %}"></script>
{% endblock content %}